{{- if .Values.mediaStreaming.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-streaming
  template:
    metadata:
      labels:
        app: media-streaming
    spec:
      containers:
      - name: server
        image: cloudsuite/media-streaming:server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  ports:
  - port: 80
  selector:
    app: media-streaming
{{- end }}
