{{- if .Values.webServing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-serving-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-serving-db
  template:
    metadata:
      labels:
        app: web-serving-db
        kids-label: "0"
    spec:
      containers:
      - name: db
        image: cloudsuite/web-serving:db_server
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: web-serving-db
spec:
  ports:
  - port: 3306
  selector:
    app: web-serving-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-serving-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-serving-app
  template:
    metadata:
      labels:
        app: web-serving-app
        kids-label: "0"
    spec:
      containers:
      - name: app
        image: cloudsuite/web-serving:web_server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
          - |
            /etc/bootstrap.sh http web-service web-serving-db memcached-service
            # Ensure services are started and block
            tail -f /var/log/nginx/access.log
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  ports:
  - port: 3306
  selector:
    app: web-serving-db
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-server
spec:
  ports:
  - port: 11211
  selector:
    app: memcached
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
  - port: 80
  selector:
    app: web-serving-app
{{- end }}
