# Binary Label 0: Benign

nodeSelector:
  node-role.kubernetes.io/worker: ""

tolerations:
  - key: "role"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

dataCaching:
  enabled: true
  label: 0

mariadbSysbench:
  enabled: true
  label: 0

mediaStreaming:
  enabled: true
  label: 0
  description: "Redis in-memory store"

webServing:
  enabled: true
  label: 0

flaskTodo:
  enabled: true
  label: 0

wordpressMysql:
  enabled: true
  label: 0
