---
- name: Add Tetragon Helm repo
  ansible.builtin.shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Install Tetragon
  ansible.builtin.shell: |
    helm upgrade --install tetragon cilium/tetragon \
      --namespace kube-system \
      --set tetragon.exportDirectory=/var/run/tetragon/
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Wait for Tetragon to be ready
  ansible.builtin.command:
    cmd: kubectl rollout status daemonset tetragon -n kube-system --timeout=120s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false

- name: Apply Tetragon TracingPolicy (Syscall Monitoring)
  ansible.builtin.shell: |
    kubectl --kubeconfig ./kubeconfig apply -f {{ playbook_dir }}/../deploy/tetragon/tracing-policy-ids.yaml
  delegate_to: localhost
  become: false
  ignore_errors: true
