---
- name: Add Tetragon Helm repo
  ansible.builtin.shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
  changed_when: true

- name: Install Tetragon
  ansible.builtin.shell: |
    helm upgrade --install tetragon cilium/tetragon \
      --namespace kube-system
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Wait for Tetragon to be ready
  ansible.builtin.command:
    cmd: kubectl rollout status daemonset tetragon -n kube-system --timeout=300s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false

- name: Copy TracingPolicy file to Master
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../deployment_charts/tetragon/tracing-policy-ids.yaml"
    dest: /tmp/tracing-policy-ids.yaml
    mode: '0644'

- name: Apply Tetragon TracingPolicy (Syscall Monitoring)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/tracing-policy-ids.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: tp_apply
  until: tp_apply.rc == 0
  retries: 5
  delay: 10
  changed_when: tp_apply.rc == 0