# Source: 
# https://github.com/cilium/tetragon/blob/main/docs/content/en/docs/concepts/tracing-policy/selectors.md
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: ids-syscall-monitoring
spec:
  kprobes:
    - call: "__x64_sys_openat"
      syscall: true
    # Memory management
    - call: "__x64_sys_mmap"
      syscall: true
    - call: "__x64_sys_mprotect"
      syscall: true
    - call: "__x64_sys_brk"
      syscall: true
    # Network operations
    - call: "__x64_sys_socket"
      syscall: true
    - call: "__x64_sys_connect"
      syscall: true
    - call: "__x64_sys_accept"
      syscall: true
    - call: "__x64_sys_sendto"
      syscall: true
    - call: "__x64_sys_recvfrom"
      syscall: true
    # Process management
    - call: "__x64_sys_clone"
      syscall: true
    - call: "__x64_sys_execve"
      syscall: true
    - call: "__x64_sys_exit_group"
      syscall: true
    - call: "__x64_sys_kill"
      syscall: true
    # Timing/scheduling
    - call: "__x64_sys_nanosleep"
      syscall: true
    # I/O control
    - call: "__x64_sys_ioctl"
      syscall: true
    - call: "__x64_sys_epoll_pwait"
      syscall: true
