apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-hubble-export-config
  namespace: kube-system
data:
  flowlogs.yaml: |
    flowLogs:
    - name: all
      filePath: /var/run/cilium/hubble/events.log
      fileMaxSizeMb: 10
      fileMaxBackups: 5
      includeFilters: []
      excludeFilters: []
      fieldMask: []
    - name: kwatch-workloads
      filePath: /var/run/cilium/hubble/kwatch-workloads.log
      fileMaxSizeMb: 200
      fileMaxBackups: 10
      includeFilters:
      - source_label:
        - "k8s:io.kubernetes.pod.namespace=default"
        - "k8s:io.kubernetes.pod.namespace=malicious"
        - "k8s:io.kubernetes.pod.namespace=benign-workloads"
      - destination_label:
        - "k8s:io.kubernetes.pod.namespace=default"
        - "k8s:io.kubernetes.pod.namespace=malicious"
        - "k8s:io.kubernetes.pod.namespace=benign-workloads"
      excludeFilters: []
      fieldMask:
      - time
      - traffic_direction
      - source
      - destination
      - verdict
      - is_reply
      - l4
      - Type
