---
- name: Add Cilium Helm repo
  ansible.builtin.shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
  changed_when: true

- name: Copy Hubble chart from local to remote
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../deploy/cilium/hubble-values.yaml"
    dest: /tmp/hubble-values.yaml
    mode: '0644'

- name: Install Cilium <v1.19>
  ansible.builtin.shell: |
    helm upgrade --install cilium cilium/cilium \
      --version 1.19.2 \
      --namespace kube-system \
      --set operator.replicas=1 \
      --set k8sServiceHost={{ wg_master_ip }} \
      --set k8sServicePort=6443 \
      --set kubeProxyReplacement=true \
      --set socketLB.enabled=true \
      --set routingMode=tunnel \
      --set tunnelProtocol=vxlan \
      --set mtu=1450 \
      --set devices=eth0 \
      --set bpf.hostLegacyRouting=false \
      --set ipam.operator.clusterPoolIPv4PodCIDRList='{10.42.0.0/16}' \
      --set hubble.enabled=true \
      --set hubble.tls.enabled=false \
      --set hubble.relay.enabled=true \
      --set hubble.relay.hostNetwork=false \
      --set hubble.relay.dnsPolicy=ClusterFirst \
      --set hubble.relay.retryTimeout=30s \
      --set hubble.relay.dialTimeout=10s \
      --set hubble.relay.tls.enabled=false \
      --set hubble.relay.tls.server.enabled=false \
      --set hubble.relay.tls.client.enabled=false \
      --set hubble.ui.enabled=true \
      --set hubble.ui.replicas=1 \
      --set hubble.listenAddress=":4244" \
      --set hubble.maxFlows=16384 \
      --set hubble.peerService.enabled=true \
      --set hubble.peerService.targetPort=4244 \
      --set hubble.peerService.clusterDomain=cluster.local \
      -f /tmp/hubble-values.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Wait for Cilium and Hubble components
  ansible.builtin.shell: |
    kubectl rollout status ds/cilium -n kube-system --timeout=120s
    kubectl rollout status deployment/hubble-relay -n kube-system --timeout=120s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false