---
- name: Get worker node names from Kubernetes
  ansible.builtin.shell: |
    kubectl get nodes --no-headers \
      --selector='!node-role.kubernetes.io/control-plane' \
      -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: worker_node_names
  changed_when: false

- name: Label worker nodes
  ansible.builtin.shell: |
    kubectl label node {{ item }} node-role.kubernetes.io/worker=worker --overwrite
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  loop: "{{ worker_node_names.stdout_lines | select('ne', '') | list }}"
  when: worker_node_names.stdout_lines | length > 0
  ignore_errors: true

- name: Install Kube Dashboard
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Copy Security Demo manifest to Master
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../deploy/demo-hubble.yaml"
    dest: /tmp/demo-hubble.yaml
    mode: '0644'

- name: Apply Security Demo (Frontend & Malicious)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/demo-hubble.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"