fullnameOverride: "malicious-containers"

mirai:
  enabled: true
  image: mitjclinic/mirai:v0.0.1-alpha
  interval: 60
  commandOverride: false

kinsing:
  enabled: true
  image: alpine:latest
  commandOverride: true
  
teamtnt:
  enabled: true
  image: timonmat/xmr-stak-cpu
  commandOverride: false
  simulateHostMount: false