---
- name: Check if cluster already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_check

- name: Configure kubelet node-ip
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: "KUBELET_EXTRA_ARGS=--node-ip={{ wg_master_ip }}"

- name: Initialize Kubernetes cluster
  ansible.builtin.shell: |
    kubeadm init \
      --apiserver-advertise-address={{ wg_master_ip }} \
      --pod-network-cidr={{ k8s_pod_cidr }} \
      --service-cidr={{ k8s_service_cidr }} \
      --skip-phases=addon/kube-proxy \
      --node-name={{ inventory_hostname }}
  when: not kubeadm_init_check.stat.exists

- name: Setup kubeconfig for agent007 and root
  ansible.builtin.shell: |
    mkdir -p /home/{{ ansible_user }}/.kube /root/.kube
    cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chown -R {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube
  changed_when: true

- name: Fetch kubeconfig and join command
  ansible.builtin.shell: |
    kubeadm token create --print-join-command > /tmp/kubeadm_join_command
  changed_when: false

- name: Fetch files to controller
  ansible.builtin.fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    flat: yes
  loop:
    - { src: "/etc/kubernetes/admin.conf", dest: "./kubeconfig" }
    - { src: "/tmp/kubeadm_join_command", dest: "./kubeadm_join_command" }

- name: Install Helm, Cilium, Hubbl
  ansible.builtin.shell: |
    # Helm
    if ! command -v helm &> /dev/null; then
      curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    fi
    # Cilium CLI
    if ! command -v cilium &> /dev/null; then
      CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
      curl -L --fail https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-amd64.tar.gz | tar xzvf - -C /usr/local/bin
    fi
    # Hubble CLI
    if ! command -v hubble &> /dev/null; then
      HUBBLE_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/hubble/main/stable.txt)
      curl -L --fail https://github.com/cilium/hubble/releases/download/$HUBBLE_VERSION/hubble-linux-amd64.tar.gz | tar xzvf - -C /usr/local/bin
    fi
  changed_when: true