---
- name: Gathering Facts
  hosts: all
  become: true
  remote_user: ubuntu

- name: Setup Configuration & Tools
  hosts: all
  become: true
  roles: [config]

- name: Setup Base Kubernetes
  hosts: all
  become: true
  roles: [k8s-base]

- name: Setup Master
  hosts: masters
  become: true
  roles: [master]

- name: Setup Worker
  hosts: workers
  become: true
  roles: [worker]

- name: Setup Cilium & Hubble
  hosts: masters
  become: true
  roles: [cilium]

- name: Setup Tetragon
  hosts: masters
  become: true
  roles: [tetragon]

- name: Apply Node Labels & Taints
  hosts: masters
  become: true
  tasks:
    - name: Label and taint k8s-worker
      ansible.builtin.shell: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl label node k8s-worker node-role.kubernetes.io/worker="" --overwrite
        kubectl taint node k8s-worker role=worker:NoSchedule --overwrite
      changed_when: true

    - name: Label and taint k8s-worker-2
      ansible.builtin.shell: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl label node k8s-worker-2 node-role.kubernetes.io/worker="" --overwrite
        kubectl taint node k8s-worker-2 role=worker:NoSchedule --overwrite
      changed_when: true

    - name: Label and taint k8s-siem
      ansible.builtin.shell: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl label node siem node-role.kubernetes.io/siem="" --overwrite
        kubectl taint node siem role=siem:NoSchedule --overwrite
      changed_when: true