---
- name: Gathering Facts
  hosts: all
  become: true
  remote_user: agent007

- name: Setup WireGuard Private Network
  hosts: all
  become: true
  roles: [wireguard]

- name: Setup Base Kubernetes
  hosts: all
  become: true
  roles: [k8s-base]

- name: Setup Master
  hosts: master
  become: true
  roles: [master]

- name: Setup Worker
  hosts: worker
  become: true
  roles: [worker]

- name: Setup Safety Networking (Cilium + Hubble)
  hosts: master
  become: true
  roles: [cilium]

- name: Setup Security Monitoring (Tetragon)
  hosts: master
  become: true
  roles: [tetragon]

- name: Manage Cluster
  hosts: master
  become: true
  roles: [manage-cluster]