---
- name: Gathering Facts
  hosts: all
  become: true
  remote_user: ubuntu

- name: Setup Configuration & Tools
  hosts: all
  become: true
  roles: [config]

- name: Setup Base Kubernetes
  hosts: all
  become: true
  roles: [k8s-base]

- name: Setup Master
  hosts: masters
  become: true
  roles: [master]

- name: Setup Worker
  hosts: workers
  become: true
  roles: [worker]

- name: Setup Cilium & Hubble
  hosts: masters
  become: true
  roles: [cilium]

- name: Setup Tetragon
  hosts: masters
  become: true
  roles: [tetragon]