---
- name: Configure kubelet node-ip
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: "KUBELET_EXTRA_ARGS=--node-ip={{ wg_worker_ip }}"

- name: Copy join command to worker
  ansible.builtin.copy:
    src: ./kubeadm_join_command
    dest: /tmp/kubeadm_join_command
    mode: '0755'

- name: Join cluster
  ansible.builtin.shell: |
    if [ ! -f /etc/kubernetes/kubelet.conf ]; then
      bash /tmp/kubeadm_join_command --node-ip={{ wg_worker_ip }}
    fi
  changed_when: true

- name: Open Hubble port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "4244"
    jump: ACCEPT
    action: insert