apiVersion: v1
kind: Namespace
metadata:
  name: benign-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-server
  namespace: benign-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: server
        image: cloudsuite/data-caching:server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-service
  namespace: benign-workload
spec:
  ports:
  - port: 11211
  selector:
    app: memcached
