apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-serving-db
  namespace: benign-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-db
  template:
    metadata:
      labels:
        app: web-db
    spec:
      containers:
      - name: db
        image: cloudsuite/web-serving:db_server
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-serving-app
  namespace: benign-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: app
        image: cloudsuite/web-serving:web_server
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: benign-workload
spec:
  ports:
  - port: 80
  selector:
    app: web-app
