hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    retryTimeout: 30s
    dialTimeout: 5s
    listenPort: "4245"
    tls:
      client:
        enabled: false
      server:
        enabled: false
  ui:
    enabled: true
    replicas: 1
    backend:
      hubbleRelayAddress: "hubble-relay:80"
  export:
    enabled: true
    bufferSize: 16384
  maxFlows: 16384
  tls:
    enabled: false
  listenAddress: ":4244"
  socketPath: "/var/run/cilium/hubble.sock"
