apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: ids-syscall-monitoring
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "path"
        - index: 1
          type: "string"
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_openat"
      syscall: true
      args:
        - index: 1
          type: "string"
        - index: 2
          type: "int"
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_socket"
      syscall: true
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"
        - index: 2
          type: "int"
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_connect"
      syscall: true
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "sockaddr"
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_read"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_write"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_close"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_mmap"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_sendto"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_recvfrom"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_clone"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_kill"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_nanosleep"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_mprotect"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_munmap"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_brk"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_rt_sigaction"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_access"
      syscall: true
      selectors:
        - matchActions:
            - action: Post
