apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: ids-syscall-monitoring
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "path" # path
        - index: 1
          type: "string" # argv
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_openat"
      syscall: true
      args:
        - index: 1
          type: "string" # filename
        - index: 2
          type: "int" # flags
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_socket"
      syscall: true
      args:
        - index: 0
          type: "int" # domain
        - index: 1
          type: "int" # type
        - index: 2
          type: "int" # protocol
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_connect"
      syscall: true
      args:
        - index: 0
          type: "int" # fd
        - index: 1
          type: "sockaddr" # addr
      selectors:
        - matchActions:
            - action: Post
    - call: "sys_read"
      syscall: true
    - call: "sys_write"
      syscall: true
    - call: "sys_close"
      syscall: true
    - call: "sys_mmap"
      syscall: true
    - call: "sys_sendto"
      syscall: true
    - call: "sys_recvfrom"
      syscall: true
    - call: "sys_clone"
      syscall: true
    - call: "sys_kill"
      syscall: true
    - call: "sys_nanosleep"
      syscall: true
    - call: "sys_sched_yield"
      syscall: true
    - call: "sys_epoll_pwait"
      syscall: true
    - call: "sys_newfstatat"
      syscall: true
    - call: "sys_mprotect"
      syscall: true
    - call: "sys_munmap"
      syscall: true
    - call: "sys_brk"
      syscall: true
    - call: "sys_rt_sigaction"
      syscall: true
    - call: "sys_access"
      syscall: true
